# -*- coding: utf-8 -*-
import os
from docx import Document
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml.ns import qn
from docx.oxml import OxmlElement

base = r"C:\Users\carlo\OneDrive\Área de Trabalho\Soluções & TAO\Manuais"
REAL = r"C:\Users\carlo\tao-crm\_manuais\real"
OUT  = os.environ.get("OPMAN_OUT", os.path.join(base, "Manual_TAO_CRM_Neo_v11.docx"))

doc = Document()
for s in doc.sections:
    s.top_margin = Inches(0.8); s.bottom_margin = Inches(0.8)
    s.left_margin = Inches(0.9); s.right_margin = Inches(0.9)
doc.styles["Normal"].font.name = "Calibri"
doc.styles["Normal"].font.size = Pt(11)

_ch = [0]; _sec = [0]
def PARTE(t):
    doc.add_page_break()
    p = doc.add_paragraph(); p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    r = p.add_run(t); r.bold = True; r.font.size = Pt(22); r.font.color.rgb = RGBColor(0x15,0x2C,0x42)
    doc.add_paragraph()
def H1(t):
    _ch[0] += 1; _sec[0] = 0
    doc.add_heading(f"{_ch[0]}. {t}", level=1)
def H2(t):
    _sec[0] += 1
    doc.add_heading(f"{_ch[0]}.{_sec[0]} {t}", level=2)
def H3(t): doc.add_heading(t, level=3)
def P(t=""): doc.add_paragraph(t)
def B(t): doc.add_paragraph(t, style="List Bullet")
def N(t): doc.add_paragraph(t, style="List Number")
def PB(): doc.add_page_break()
def CAP(t):
    cp = doc.add_paragraph(); cp.alignment = WD_ALIGN_PARAGRAPH.CENTER
    r = cp.add_run(t); r.italic = True; r.font.size = Pt(9.5); r.font.color.rgb = RGBColor(0x66,0x66,0x66)
def IMG(fname, caption=None, w=6.3):
    path = os.path.join(REAL, fname)
    if os.path.exists(path):
        p = doc.add_paragraph(); p.alignment = WD_ALIGN_PARAGRAPH.CENTER
        p.add_run().add_picture(path, width=Inches(w))
        if caption: CAP(caption)
    else:
        P("[imagem: " + fname + "]")
def TOC():
    p = doc.add_paragraph(); r = p.add_run()._r
    b = OxmlElement('w:fldChar'); b.set(qn('w:fldCharType'),'begin'); r.append(b)
    i = OxmlElement('w:instrText'); i.set(qn('xml:space'),'preserve'); i.text='TOC \\o "1-3" \\h \\z \\u'; r.append(i)
    s = OxmlElement('w:fldChar'); s.set(qn('w:fldCharType'),'separate'); r.append(s)
    t = OxmlElement('w:t'); t.text="Abra no Word e clique com o botão direito aqui > Atualizar campo."; r.append(t)
    e = OxmlElement('w:fldChar'); e.set(qn('w:fldCharType'),'end'); r.append(e)

# ───── CAPA ─────
tp = doc.add_paragraph(); tp.alignment = WD_ALIGN_PARAGRAPH.CENTER
r = tp.add_run("TAO Neo"); r.bold=True; r.font.size=Pt(40); r.font.color.rgb=RGBColor(0x15,0x2C,0x42)
st = doc.add_paragraph(); st.alignment = WD_ALIGN_PARAGRAPH.CENTER
r = st.add_run("Manual de Operação do Sistema"); r.font.size=Pt(20); r.font.color.rgb=RGBColor(0x55,0x60,0x70)
sd = doc.add_paragraph(); sd.alignment = WD_ALIGN_PARAGRAPH.CENTER
r = sd.add_run("Configuração e operação — do WhatsApp ao recebimento"); r.italic=True; r.font.size=Pt(12)
vs = doc.add_paragraph(); vs.alignment = WD_ALIGN_PARAGRAPH.CENTER
r = vs.add_run("Versão v11 — 02/08/2026"); r.font.size=Pt(11); r.font.color.rgb=RGBColor(0x88,0x90,0x9a)
P(); P()
P("Este manual leva qualquer pessoa do zero à operação: a Parte A ensina a CONFIGURAR o sistema (negócio, WhatsApp, Agente, CRM, Fórmulas e Caixa) e a Parte B mostra como OPERAR no dia a dia, seguindo a jornada real do cliente. Onde houver telas, elas são reais do sistema.")
PB()
doc.add_heading("Sumário", level=1); TOC()

# ════════════════════════ PARTE A — CONFIGURAÇÃO ════════════════════════
PARTE("PARTE A — CONFIGURAÇÃO (colocar o sistema em operação)")

H1("Antes de começar")
P("A configuração é feita por um Administrador. Faça uma vez, na ordem abaixo, e o sistema fica pronto para operar.")
P("Pré-requisitos:")
B("Acesso ao portal como Administrador (e-mail e senha).")
B("Um número de WhatsApp dedicado ao atendimento.")
B("Os serviços de base (servidor de mensagens/automação) já provisionados pela TAO — você só conecta.")
B("As informações do negócio: identidade, catálogo/serviços, horário, formas de pagamento e, para manipulação, formas farmacêuticas e tabela de ativos.")
P("Ordem recomendada (cada item é um capítulo a seguir):")
N("Cadastrar o Negócio e as Categorias.")
N("Criar os Usuários e definir perfis.")
N("Conectar o WhatsApp.")
N("Configurar o Agente (chatbot).")
N("Configurar o CRM (workspace, integração, pipelines, campos, automações, horário…).")
N("Configurar as Fórmulas (formas, ativos/sinônimos, IA).")
N("Configurar o Caixa (operadoras, taxas, formas de pagamento).")
N("Rodar o checklist de go-live.")

H1("Negócio e Categorias")
P("Tudo no TAO Neo pertence a um Negócio. Comece cadastrando o seu.")
H2("Cadastrar o Negócio")
P("Vá em Configurações > Geral > Negócios. Crie/edite o negócio e preencha a identidade que o Agente usará no atendimento: nome do negócio, persona (como o robô se apresenta e se comporta), apresentação inicial e as instruções de comportamento. É aqui que o chatbot ganha 'personalidade'.")
IMG("real_cfg_negocios.png", "Configurações > Geral > Negócios.")
H2("Categorias")
P("Em Configurações > Agente > Categorias, crie as categorias que organizam o catálogo (ex.: linhas de produto, tipos de serviço). Elas ajudam o Agente a apresentar as opções de forma organizada.")
IMG("real_cfg_categorias.png", "Configurações > Agente > Categorias.")

H1("Usuários e perfis")
P("Em Configurações > Geral > Usuários, cadastre quem vai acessar o sistema. Para cada pessoa: nome, e-mail (que é o login), senha inicial, perfil e negócio.")
P("Perfis disponíveis:")
B("Operacional (atendente) — opera o dia a dia (Kanban, Inbox, cards, fórmulas); não acessa configurações.")
B("Gestor — tudo do operacional, mais configurações, usuários e o Caixa.")
B("Administrador — acesso completo.")
P("O e-mail não pode ser alterado depois de criado (apenas a senha e o nome).")
IMG("real_usuarios.png", "Configurações > Geral > Usuários.")

H1("Conectar o WhatsApp")
P("Em Configurações > Geral > Conectores, ficam os dados de conexão do WhatsApp (servidor de mensagens e instância). É o que liga o Agente e o CRM ao número de atendimento.")
N("Confira ou informe os dados do conector (endereço do servidor e nome da instância) — normalmente já vêm pré-configurados pela TAO.")
N("Conecte a instância (leitura do QR Code do WhatsApp, quando aplicável).")
N("Verifique o indicador de status: a instância precisa aparecer como conectada.")
P("Uma mesma empresa pode ter mais de uma instância (multi-instância) — cada número é identificado automaticamente e direcionado ao negócio correto.")
IMG("real_cfg_conectores.png", "Configurações > Geral > Conectores.")

H1("Configurar o Agente (chatbot)")
P("O Agente é o atendimento automático. Além da persona (definida no Negócio), configure o que ele conhece e quando responde.")
H2("Catálogo")
P("Em Configurações > Agente > Catálogo, cadastre os produtos/serviços (nome, preço, descrição) que o Agente pode apresentar e usar para montar pedidos.")
IMG("real_cfg_catalogo.png", "Configurações > Agente > Catálogo.")
H2("Campos Extras")
P("Em Campos Extras você define informações adicionais que o Agente coleta nos atendimentos/leads (ex.: dados específicos do seu negócio).")
IMG("real_cfg_campos_extras.png", "Configurações > Agente > Campos Extras.")
H2("Disponibilidade")
P("Defina os horários em que o Agente atende. Fora desses horários ele informa o cliente e registra a conversa para retorno.")
IMG("real_cfg_disponibilidade.png", "Configurações > Agente > Disponibilidade.")
H2("Promoções e Avisos")
P("Cadastre mensagens de promoções/avisos que o Agente pode comunicar durante o atendimento.")
IMG("real_cfg_conteudo.png", "Configurações > Agente > Promoções/Avisos.")

H1("Configurar o CRM")
P("O CRM é onde o atendimento humano acontece. A configuração tem seu próprio menu (Configurações > CRM > Configurações), com uma navegação lateral por seções: Global, Configuração, Operação e Sistema.")
H2("Workspaces")
P("O workspace é o 'espaço de trabalho' do CRM, vinculado a um negócio. Em geral já existe um por negócio. Confirme que o seu negócio tem um workspace ativo.")
IMG("real_cfg_workspaces.png", "CRM > Configurações > Workspaces.")
H2("Integração (conectar o CRM ao WhatsApp)")
P("Na seção Integração ficam a chave de segurança (X-Tao-Key) do workspace e a URL de webhook que recebe as mensagens. Essa configuração faz as mensagens do WhatsApp virarem cards automaticamente. Em geral já vem pronta; confira se a chave existe e se o webhook está apontado corretamente.")
IMG("real_cfg_integracao.png", "CRM > Configurações > Integração.")
H2("Pipelines & Estágios")
P("Os pipelines são os funis. O TAO Neo trabalha com dois em série: Funil de Vendas e Pós-Vendas. Os cards ganhos no Funil de Vendas vão automaticamente para o Pós-Vendas.")
N("Selecione o pipeline (Funil de Vendas ou Pós-Vendas) nas abas no topo. Para criar outro, use 'Novo pipeline' (nome + ordem).")
N("Marque qual pipeline é o de Pós-vendas usando a opção 'Usar pipeline selecionado como Pós-vendas'.")
N("Na lista de ESTÁGIOS, defina as etapas do funil: nome, cor e TIPO.")
N("O TIPO determina o comportamento da etapa: Normal (etapa comum), Handoff (marca que o atendimento aguarda humano) e os terminais Ganho e Perdido (fecham o card). É o estágio de Ganho que dispara o envio para o Pós-Vendas e a criação da venda no Caixa.")
IMG("real_cfg_pipelines.png", "CRM > Configurações > Pipelines & Estágios.")
H2("Campos")
P("Em Campos você cria os campos do negócio que aparecem no card (texto, número, seleção, data, arquivo etc.). Pode marcar campos como obrigatórios e vinculá-los a estágios — assim o sistema exige o preenchimento antes de avançar/fechar.")
IMG("real_cfg_campos.png", "CRM > Configurações > Campos.")
H2("Automações")
P("As automações fazem o sistema agir sozinho. Cada automação tem um gatilho e uma ação.")
B("Gatilhos: tempo numa fase (card parado), cliente sem resposta, entre outros.")
B("Ações: enviar mensagem (com modelo de texto), mover de fase, atribuir responsável, aplicar tag.")
P("Use-as para padronizar o atendimento (ex.: cobrar retorno após X horas, mover automaticamente, avisar o time).")
IMG("real_cfg_automacoes.png", "CRM > Configurações > Automações.")
H2("Equipe")
P("Defina quem são os atendentes do workspace e como os cards são distribuídos entre eles.")
IMG("real_cfg_equipe.png", "CRM > Configurações > Equipe.")
H2("Horário de atendimento")
P("Configure os dias e horários de funcionamento (por dia da semana, abertura e fechamento). Isso é importante por dois motivos: o sistema responde/aguarda conforme o expediente e os indicadores de tempo dos painéis (TMR e TMA) passam a contar apenas as horas dentro do expediente — não inflando com noites e fins de semana.")
IMG("real_cfg_horario.png", "CRM > Configurações > Horário de atendimento.")
H2("SLA, CSAT, Metas, Tags, Templates e Webhooks")
P("Complete a configuração conforme a necessidade:")
B("SLA — prazos por estágio (alerta quando um card passa do tempo).")
B("CSAT — pesquisa de satisfação ao final do atendimento.")
B("Metas — metas por atendente, acompanhadas no painel.")
B("Tags — etiquetas para classificar os cards.")
B("Templates — respostas prontas que o atendente insere no chat do card.")
B("Webhooks — notificações para sistemas externos quando cards são criados, movidos ou fechados.")
IMG("real_cfg_tags.png", "CRM > Configurações > Tags (exemplo de seção de configuração).")

H1("Configurar as Fórmulas")
P("Para farmácias de manipulação, configure o módulo Fórmulas antes de cotar.")
H2("Formas Farmacêuticas")
P("Em Configurações > Fórmulas > Formas Farmacêuticas, cadastre as formas (cápsula, creme, solução etc.) com seus parâmetros (volume, cápsulas, custo fixo, margem, valor mínimo).")
IMG("real_formula_formas.png", "Configurações > Fórmulas > Formas Farmacêuticas.")
H2("Ativos e Sinônimos")
P("Em Fórmulas > Ativos ficam as matérias-primas e embalagens (em geral sincronizadas do sistema de origem). Cadastre os SINÔNIMOS de cada ativo: são os nomes alternativos (comercial, abreviação, grafias) que fazem o sistema reconhecer o ativo mesmo quando a receita usa outro nome. É possível gerar sinônimos em massa com IA. Quanto melhor essa base, mais a leitura automática de receitas acerta.")
IMG("real_formula_ativos.png", "Configurações > Fórmulas > Ativos e sinônimos.")
H2("Configurações de Fórmulas (margem e IA)")
P("Defina a margem padrão e as chaves de inteligência artificial. As chaves de IA são o que habilita a leitura de receitas por foto/PDF — o grande diferencial do módulo (ver Parte B, capítulo de Fórmulas).")
IMG("real_cfg_formula_config.png", "Configurações > Fórmulas > Configurações (margem e chaves de IA).")

H1("Configurar o Caixa")
P("O Caixa é operado por Administradores e Gestores. Configure nesta ordem:")
H2("Operadoras de Cartão")
P("Cadastre as operadoras (adquirentes) com a taxa de antecipação, em Configurações > Caixa > Operadoras de Cartão.")
IMG("real_cfg_caixa_adq.png", "Configurações > Caixa > Operadoras de Cartão.")
H2("Formas de Pagamento")
P("Cadastre as formas (dinheiro, PIX, débito, crédito, link, boleto) com o tipo e o canal. Marque quais entram no fechamento de dinheiro da gaveta.")
IMG("real_cfg_caixa_formas.png", "Configurações > Caixa > Formas de Pagamento.")
H2("Taxas (MDR)")
P("Para as formas de cartão, cadastre a taxa e o prazo de recebimento por faixa de parcelas (ex.: 1x, 2–3x, 4–6x), ancorados na forma. É isso que calcula o valor líquido e a data prevista de cada recebimento.")
IMG("real_cfg_caixa_taxas.png", "Configurações > Caixa > Taxas (MDR).")

H1("Checklist de go-live")
P("Antes de liberar para o time, confirme:")
N("Negócio cadastrado com persona/apresentação e categorias.")
N("Usuários criados com os perfis corretos.")
N("WhatsApp conectado (instância aparece como conectada).")
N("Agente com catálogo, disponibilidade e campos extras.")
N("CRM: workspace ativo, integração/webhook ok, pipelines (Funil + Pós-vendas) com estágios e os terminais Ganho/Perdido definidos, campos obrigatórios, automações e horário de atendimento.")
N("Fórmulas: formas cadastradas, base de ativos/sinônimos e chaves de IA (se for usar leitura de receita).")
N("Caixa: operadoras, formas de pagamento e taxas (MDR).")
N("LGPD: aviso de privacidade ativo no primeiro contato do Agente e base legal/consentimento para o tratamento dos dados registrados (conversas, cadastro, histórico). Defina também o responsável pelas solicitações de titular (acesso/exclusão) — o direito ao esquecimento é atendido pela Anonimização no cadastro do cliente.")
N("Backup e retenção: confirme que a rotina de backup dos dados está ativa e saiba a janela de retenção. Para manipulação, a rastreabilidade das OMs é preservada mesmo após anonimizar o paciente.")
N("Contingência: tenha o plano para quando o WhatsApp cair (reconectar a instância nos Conectores) e um canal alternativo de atendimento; combine com a TAO o contato de suporte e o tempo de resposta.")
N("Teste de ponta a ponta: mande uma mensagem de teste no WhatsApp e acompanhe o card nascer no CRM; faça um orçamento; feche como Ganho; receba no Caixa.")
P("Observação sobre módulos: o sistema é modular e as telas visíveis seguem o contrato de cada cliente — um módulo não contratado não aparece no menu. Este manual descreve a suíte completa.")

# ════════════════════════ PARTE B — OPERAÇÃO ════════════════════════
PARTE("PARTE B — OPERAÇÃO (uso no dia a dia)")

H1("Visão geral da operação")
P("Com o sistema configurado, a operação segue a jornada do cliente. As próximas seções acompanham exatamente esta ordem:")
N("O cliente chama no WhatsApp. O Agente atende, responde e qualifica.")
N("O atendimento vira um card no CRM (Funil de Vendas). Quando precisa de uma pessoa, fica aguardando atendimento humano.")
N("O atendente assume o card, conversa pelo chat e, quando é o caso, cota uma fórmula ali dentro — pela foto/PDF da receita (IA), importando do sistema de origem ou montando manualmente.")
N("O orçamento fica preso ao card e vira o valor do negócio. O farmacêutico revisa e aprova.")
N("O atendente fecha como Ganho: o card vai para o Pós-Vendas e nasce a venda no Caixa.")
N("O Caixa recebe o pagamento e, depois, concilia os cartões.")
N("O Pós-Vendas acompanha produção e entrega até o cliente receber.")

H1("Acesso e navegação")
H2("Entrar no sistema")
P("Acesse o portal, informe e-mail e senha (o e-mail é o login). Use 'Esqueci minha senha' se precisar.")
IMG("real_login.png", "Tela de login do TAO Neo.")
H2("O menu lateral")
P("O menu é organizado por módulo, cada um aparecendo uma vez: Visão Geral, Agente, CRM, Fórmulas, Caixa e Configurações. Em celulares, toque no ícone de menu (≡) para abri-lo.")
IMG("real_visao_geral.png", "Portal do TAO Neo — menu lateral por módulo.")

H1("O Agente (atendimento automático no WhatsApp)")
P("O Agente conversa com o cliente no WhatsApp 24h: responde, qualifica e, quando necessário, encaminha para um atendente. Tudo alimenta o CRM.")
H2("Painel do Agente")
P("Mostra o desempenho do período: Conversas, Leads, Pedidos, Faturamento, Conversão, TMR (tempo de resposta) e TMA (tempo de atendimento) — estes dois contando apenas o horário de atendimento configurado —, além do gráfico Conversas × Leads × Pedidos por dia e do filtro por negócio.")
IMG("real_agente.png", "Painel do Agente.")
H2("Leads, Pedidos e Histórico")
P("No módulo Agente você acompanha os Leads captados, os Pedidos registrados e o Histórico completo das conversas.")
IMG("real_leads.png", "Agente — lista de Leads.")
H2("Do Agente para o atendente")
P("Quando o cliente precisa de uma pessoa, o Agente faz o handoff: marca o atendimento como aguardando humano e o card aparece no CRM para ser assumido.")

H1("CRM — Funil de Vendas (Kanban)")
P("Cada conversa vira um card, que caminha pelas etapas (colunas) do funil até o fechamento.")
IMG("real_crm_kanban.png", "CRM — Funil de Vendas (Kanban).")
H2("Lendo um card")
P("O card mostra nome e telefone do cliente, etapa, etiquetas, valor (quando houver orçamento) e sinais: ponto vermelho = mensagem não lida; destaque = aguardando atendimento humano.")
H2("Filtros, busca e atualização")
P("Acima do quadro há filtros (atendente, etapa, status, tag) e busca por nome/telefone. O quadro se atualiza sozinho no intervalo escolhido.")
H2("Inbox — a visão de mensagens")
P("O botão Inbox/Kanban alterna a mesma informação para uma lista de conversas ordenada pela última mensagem — ideal para trabalhar 'estilo caixa de entrada'.")
IMG("real_crm_inbox.png", "CRM — visão Inbox (dentro do Kanban).")

H1("O Card de Atendimento")
P("Abrir um card mostra, de um lado, as informações e campos do negócio; do outro, o chat do WhatsApp.")
IMG("real_card.png", "Tela do card — informações e chat do WhatsApp.")
H2("Conversando pelo chat")
P("Responda o cliente diretamente no WhatsApp pelo chat do card; as mensagens chegam e saem em tempo real e ficam no histórico.")
H2("Campos e itens do negócio")
P("Preencha os campos do negócio (alguns podem ser obrigatórios) e registre itens. A soma dos itens e dos orçamentos forma o valor da oportunidade.")
H2("Mover o card e devolver ao chatbot")
P("Use 'Mover para' para avançar a etapa e 'Devolver ao chatbot' para o Agente voltar a responder automaticamente aquele cliente.")

H1("Fórmulas — cotação de manipulados (integrada ao CRM)")
P("Fórmulas é um módulo tão central quanto o CRM: transforma uma receita em orçamento, dentro do próprio atendimento. O orçamento nasce no card, vira o valor do negócio e, ao fechar a venda, segue para o Caixa — sem digitação dupla. Há três formas de cotar; comece pela mais automática.")
H2("A receita vira orçamento — por foto ou PDF (IA)")
P("O maior diferencial: o cliente manda a foto ou o PDF da receita pelo WhatsApp e a inteligência artificial lê a prescrição e monta o orçamento sozinha, pronto para a conferência do farmacêutico.")
N("O cliente envia a imagem (JPG/PNG) ou o PDF da receita.")
N("A IA identifica a forma farmacêutica, os ativos e as doses.")
N("O sistema casa cada ativo com o cadastro — inclusive reconhecendo nomes alternativos (sinônimos).")
N("O orçamento é criado em 'pendente de revisão', vinculado ao cliente, para o farmacêutico aprovar.")
P("Formatos: JPG, PNG e PDF (até ~20 MB). A IA acelera, mas a palavra final é do farmacêutico.")
H2("Sinônimos — entender o ativo por qualquer nome")
P("Receitas usam nomes variados para o mesmo ativo. A base de sinônimos (configurada na Parte A) é o que faz o reconhecimento — manual ou por IA — acertar mesmo sem o nome oficial.")
IMG("real_formula_ativos.png", "Fórmulas — Ativos e sinônimos.")
H2("Importar do sistema de origem")
P("Se o orçamento já existe no sistema de origem: no card, cole o texto do orçamento. O sistema separa os itens, casa os ativos (por nome, código ou sinônimo), calcula cápsulas e monta o quadro de valores, fechando no valor final do sistema de origem.")
H2("Montar manualmente")
P("Em Fórmulas > Novo Orçamento (ou pelo card): escolha a forma e a quantidade; adicione os ativos (dose, unidade, QSP); adicione a embalagem; confira o quadro (Calculado → Custo Fixo → Cápsulas → Sub-Total → Acréscimo → Sem Desconto → Desconto → Valor com Desconto) e salve.")
IMG("real_formula_novo.png", "Fórmulas — editor de Novo Orçamento.")
H2("O orçamento no card e a revisão")
P("Por qualquer caminho, o orçamento fica preso ao card e vira o valor da oportunidade. Em negociação, todos os orçamentos do card são somados; quando o negócio é ganho e vai ao Pós-Vendas, o valor passa a considerar SÓ os orçamentos aprovados (os que viraram OM). Em Fórmulas > Orçamentos, o farmacêutico Aprova, Rejeita ou Marca como Enviado (status: pendente → aprovado → enviado).")
B("Aprovar em lote: marque os orçamentos na caixa de seleção e clique em '✅ Aprovar selecionados' — cada um vira uma OM de uma vez. Aprovar é exclusivo do farmacêutico responsável.")
IMG("real_formula_orc.png", "Fórmulas — Orçamentos e revisão (com seleção em lote).")

H1("Fechando o negócio")
H2("Fechar como Ganho")
P("Quando o cliente fecha a compra, encerre o card como Ganho. Para fechar, o sistema exige pelo menos UM orçamento APROVADO (que virou OM) OU um item de negócio — um orçamento só criado, ainda não aprovado, não fecha o negócio. Também pede o Valor Final e os campos obrigatórios. Ao confirmar: o card vai para o Pós-Vendas (o valor já recalculado só com os orçamentos aprovados) e nasce uma venda a receber no Caixa.")
H2("Fechar como Perdido")
P("Se o negócio não avança, encerre como Perdido e informe o motivo. O card sai do funil ativo e fica registrado.")

H1("Pós-Vendas (produção e entrega)")
P("Os cards ganhos caem no funil de Pós-Vendas — com etapas de produção e entrega (ex.: Aguardando Produção, Em Produção, Pronto para Entrega, pesquisa de satisfação). O objetivo é garantir que o cliente receba o pedido.")
IMG("real_pos_vendas.png", "CRM — funil de Pós-Vendas.")
P("No card há 'Receber pagamento', que leva direto ao recebimento no Caixa.")
P("Este manual cobre a jornada comercial (atendimento → venda → recebimento). A PRODUÇÃO em si — Ordem de Manipulação, pesagem, escolha de lote, ficha, rótulo, controle de estoque e controlados — é detalhada no Manual do TAO Lab (módulo de manipulação), que é o dono desses capítulos.")

H1("Caixa — recebimento e financeiro")
P("Regra de ouro: toda venda nasce de um card (do funil, ao ganhar, ou avulsa de balcão, que cria um card 'Consumidor Final'). O Caixa é operado por gestores e administradores.")
H2("Vendas e recebimento")
P("Em Caixa > Vendas, veja as vendas a receber (busca por nome, WhatsApp ou nº da requisição) e clique em Receber: informe forma, parcelas e valor.")
B("Split: mais de uma forma no mesmo recibo.")
B("Cupom: receber várias vendas num único recibo.")
B("A taxa (MDR), o líquido e a data prevista são calculados pela faixa de parcelas.")
B("Estorno: desfaz um recebimento (com motivo; auditado; reabre a venda).")
IMG("real_caixa_vendas.png", "Caixa — Vendas e recebimento.")
H2("Sessão / Fechamento")
P("Abra o caixa com o saldo inicial; ao fechar, informe o valor contado. O sistema mostra o esperado (inicial + dinheiro recebido) e a divergência.")
H2("Conciliação e antecipação")
P("Confira os recebíveis de cartão na data prevista (conciliar) e, se quiser, antecipe — o sistema aplica a taxa de antecipação da operadora.")
H2("Painel do Caixa")
P("Mostra, por período (Hoje, 7 dias, Mês): vendido, recebido, a receber, taxas e líquido; recebimentos por forma e por origem; e os valores a cair por data. O período 'Hoje' considera o dia atual (do começo do dia até agora).")
IMG("real_caixa.png", "Caixa — Painel financeiro.")

H1("Contatos (perfil do cliente)")
P("Em CRM > Contatos fica o cadastro central de cada cliente, com o histórico unificado (conversas, leads, pedidos, negócios) — o perfil 360°.")
IMG("real_crm_contatos.png", "CRM — Contatos.")

H1("Painéis e Indicadores (Dashboards)")
P("Acompanhe a operação pela Visão Geral (consolidado) e pelos Painéis de cada módulo.")
H2("Visão Geral")
P("Tela inicial: reúne o desempenho do Agente (conversas, leads, pedidos) e os resultados do CRM (cards abertos, novos leads, conversão, oportunidades, handoff aguardando, ganhos × perdidos).")
H2("Painel do CRM")
P("Indicadores do funil: cards por etapa, novos leads, conversão, oportunidades em aberto e ganhos × perdidos. Inclui TMA (criação → resolução do card) e TMR (1ª resposta), ambos contando apenas o horário de atendimento configurado.")
IMG("real_crm_dashboard.png", "Painel do CRM — indicadores do funil.")
H2("Painéis do Agente, Fórmulas e Caixa")
P("Cada módulo tem seu painel, já mostrado nos capítulos respectivos: Agente (conversas/leads/pedidos/TMR/TMA), Fórmulas (pendentes/aprovados/volume) e Caixa (vendido/recebido/a receber/líquido).")

H1("Administração e manutenção")
P("As telas de configuração (Parte A) ficam em Configurações e são acessadas por gestores e administradores. No dia a dia, as tarefas administrativas mais comuns são: criar/ajustar usuários, revisar automações e horário, conferir a conexão do WhatsApp e acompanhar os painéis. Para reconfigurar qualquer módulo, volte à Parte A deste manual.")

H1("Apêndice — Rotina diária do operador")
N("Abra o Kanban (ou a Inbox) e veja quem aguarda atendimento — priorize as mensagens não lidas.")
N("Assuma o card, responda pelo chat e preencha os campos do negócio.")
N("Sendo manipulação, cote a fórmula no card (foto/PDF da receita, sistema de origem ou manual) e deixe o farmacêutico aprovar.")
N("Fechou a compra? Encerre como Ganho — vai para o Pós-Vendas e gera a venda no Caixa.")
N("Receba o pagamento no Caixa e acompanhe a produção/entrega no Pós-Vendas.")
P()
P("Dúvidas comuns: um card que 'sumiu' do funil provavelmente foi fechado e está no Pós-Vendas ou no histórico; se uma mensagem não chega ao cliente, confira a conexão do WhatsApp nos Conectores.")

doc.save(OUT)
print("Salvo:", OUT)
print("Paragrafos:", len(doc.paragraphs))
