-- TAO Neo — Habilitar RLS em todas as tabelas public (v2 18/08: +contas_categorias/contas_recorrencias) (projeto Robos gclayesytzzpzkjvgede)
-- Executar no SQL Editor do Supabase APÓS as 18h. O backend usa a chave SECRET
-- (service_role) que BYPASSA o RLS, e o N8N usa credencial service_role tambem —
-- entao ligar RLS SEM policies bloqueia so o acesso anonimo/publico (nada usa hoje).
-- Rollback (se algo quebrar): ALTER TABLE <tabela> DISABLE ROW LEVEL SECURITY;

BEGIN;

ALTER TABLE public."ativo_precos_hist" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."ativos" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."ativos_sinonimos" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."caixa_adquirentes" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."caixa_emitente_fiscal" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."caixa_formas_pagamento" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."caixa_movimentos" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."caixa_pagamentos" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."caixa_recebiveis" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."caixa_recibo_vendas" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."caixa_recibos" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."caixa_sessoes" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."caixa_taxas" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."caixa_venda_itens" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."caixa_vendas" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."campanha_contatos" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."campanha_historico" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."campanha_historico_itens" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."campanhas" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."campos_extras" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."catalogo" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."catalogo_componentes" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."catalogo_disponibilidade" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."categorias" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."cid10" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."cliente_produtos" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."clientes" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."conectores_saida" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."contas_a_pagar" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."contas_pagar" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."contas_categorias" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."contas_recorrencias" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."contato_enderecos" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."conteudo_dinamico" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."cotacao_fornecedores" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."cotacao_itens" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."cotacao_modelos" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."cotacao_precos" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."cotacao_propostas" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."cotacoes" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."crm_alcadas" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."crm_automacoes" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."crm_automacoes_fila" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."crm_campos_definicao" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."crm_campos_estagio" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."crm_card_itens" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."crm_cards" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."crm_cards_historico" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."crm_cards_tags" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."crm_cards_valores" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."crm_comentarios" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."crm_contatos" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."crm_estagios" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."crm_historico" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."crm_instancias" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."crm_lembretes" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."crm_mensagens" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."crm_metas" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."crm_msg_templates" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."crm_msgs_agendadas" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."crm_nps" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."crm_perfil_usuarios" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."crm_perfis" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."crm_permissoes" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."crm_pipelines" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."crm_planos" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."crm_round_robin" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."crm_tags" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."crm_webhooks_saida" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."crm_workspaces" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."empresa_config" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."entregas" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."estoque_entradas_nf" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."estoque_entradas_nf_itens" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."estoque_forn_depara" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."estoque_movimentos" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."fiscal_produtos" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."formas_farmaceuticas" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."fornecedor_mensagens" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."fornecedores" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."hist_clientes" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."hist_formulas" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."hist_formulas_itens" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."historico" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."lab_etapas" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."lab_formulas_padrao" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."lab_formulas_padrao_itens" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."lab_inventario" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."lab_inventario_itens" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."lab_laudo_ensaios" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."lab_laudos" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."lab_lotes_mp" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."lab_ordem_etapas" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."lab_ordem_itens" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."lab_ordens" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."lab_producao" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."lab_producao_itens" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."lab_producoes_internas" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."lab_rotulo_templates" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."lab_rotulos" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."laudo_modelos" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."leads" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."lgpd_acessos" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."lista_contatos_itens" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."listas_contatos" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."mensagens_buffer" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."orcamentos" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."pedidos" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."precos_historico" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."prescritores" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."recebimento_depara" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."recebimento_nf" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."recebimento_nf_itens" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."receita_logs" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."sngpc_arquivos" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."sngpc_movimentos" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."tipos_capsula" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."unidades_medida" ENABLE ROW LEVEL SECURITY;

COMMIT;

-- Conferir depois (deve listar todas com rowsecurity=true):
-- SELECT tablename, rowsecurity FROM pg_tables WHERE schemaname='public' AND rowsecurity=false;
